/**
 * Enum for Icon
 * @enum
 * This enum represents the different icons used in the application.
 * Each icon is represented by a string value.
 */
export enum Icon {
	AngleDown = 'la la-angle-down',
	AngleUp = 'la la-angle-up',
	ArrowCircleLeft = 'la la-arrow-circle-left',
	ArrowLeft = 'la la-arrow-left',
	Backward = 'las la-backward',
	Bars = 'la la-bars',
	BorderAll = 'la la-border-all',
	Box = 'las la-box',
	Building = 'la la-building',
	Calendar = 'la la-calendar',
	CalendarPlus = 'la la-calendar-plus',
	Camera = 'las la-camera',
	Clock = 'la la-clock',
	Check = 'la la-check',
	Download = 'las la-download',
	EllipsisH = 'las la-ellipsis-h',
	Envelope = 'las la-envelope',
	ExclamationCircle = 'la la-exclamation-circle',
	Eye = 'la la-eye',
	EyeSlash = 'la la-eye-slash',
	Forward = 'las la-forward',
	Headset = 'la la-headset',
	Image = 'las la-image',
	List = 'la la-list',
	Map = 'la la-map',
	Microphone = 'las la-microphone',
	Mobile = 'la la-mobile',
	Music = 'la la-music',
	Pause = 'las la-pause',
	Pencil = 'la la-pencil',
	Phone = 'la la-phone',
	Play = 'las la-play',
	Plus = 'la la-plus',
	Podcast = 'la la-podcast',
	RaspberryPi = 'lab la-raspberry-pi',
	RedoAlt = 'las la-redo-alt',
	Rocket = 'la la-rocket',
	Search = 'la la-search',
	Server = 'las la-server',
	SignOutAlt = 'las la-sign-out-alt',
	Stop = 'las la-stop',
	Tasks = 'la la-tasks',
	Times = 'la la-times',
	Trash = 'las la-trash',
	Upload = 'las la-upload',
	User = 'la la-user',
	UserPlus = 'la la-user-plus',
	Users = 'las la-users',
	VolumeDown = 'las la-volume-down',
	VolumeMute = 'las la-volume-mute',
	VolumeUp = 'las la-volume-up'
}
