[package]
name = "myrts-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
log4rs = "1.2.0"
proto = { path = "../../crates/proto" }
tokio = { version = "1.33.0", features = ["full"] }
utils = { path = "../../crates/utils" }
types = { path = "../../crates/types", features = ["api", "proto"] }
proto-db = { path = "../../crates/proto-db" }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
rodio = "0.17.3"
rtc = { path = "../../crates/rtc" }
byteorder = "1.4.3"
libc = "0.2.147"
anyhow = "1.0.75"
dotenvy = "0.15.7"
systemstat = "0.2.3"
audio = { path = "../../crates/audio" }

[build-dependencies]
bindgen = "0.66.1"
pkg-config = "0.3.27"
